/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author azzai_6qal
 */
public class KonversiSuhuu extends javax.swing.JFrame {

    /**
     * Creates new form KonversiSuhuu
     */
    
   public Double input;
    public Double celcius;
    public Double fahrenheit;
    public Double reamur;
    public Double calvin;
    public String hasilcelcius;
    public String hasilfahrenheit;
    public String hasilreamur;
    public String hasilcalvin;
    
    public KonversiSuhuu() {
        initComponents();
    }
    
     /*private*/
    private void celcius() {
        input=Double.parseDouble(SuhuAwal.getText());
        
        celcius=input;
        fahrenheit=celcius*1.8+32;
        reamur=celcius*0.8;
        calvin=celcius+273.15;
        
        hasilcelcius=Double.toString(celcius);
        txtcelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtfahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtreamur.setText(hasilreamur);
        
        hasilcalvin=Double.toString(calvin);
        txtcalvin.setText(hasilcalvin);
        
    }
    
    private void  fahrenheit(){
    input  = Double.parseDouble(SuhuAwal.getText());
    
    fahrenheit=input;
    celcius=(fahrenheit-32)/1.8;
    reamur=(fahrenheit-32)/2.25;
    
   hasilcelcius=Double.toString(celcius);
        txtcelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtfahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtreamur.setText(hasilreamur);
        
        hasilcalvin=Double.toString(calvin);
        txtcalvin.setText(hasilcalvin);
            
    }
    
    private void reamur() {
    input = Double.parseDouble(SuhuAwal.getText());
      reamur=input;
      celcius=reamur/0.8;
      fahrenheit=(reamur*2.25)+32;
      calvin=reamur/0.8+237.15;
      
     hasilcelcius=Double.toString(celcius);
        txtcelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtfahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtreamur.setText(hasilreamur);
        
        hasilcalvin=Double.toString(calvin);
        txtcalvin.setText(hasilcalvin);
           
    }
    
    private void calvin() {
    input=Double.parseDouble(SuhuAwal.getText());
       
       calvin=input;
       celcius=calvin-273.15;
       fahrenheit=calvin*1.8-459.67;
       reamur=(calvin-237.15)*0.8;
       
     hasilcelcius=Double.toString(celcius);
        txtcelcius.setText(hasilcelcius);
        
        hasilfahrenheit=Double.toString(fahrenheit);
        txtfahrenheit.setText(hasilfahrenheit);
        
        hasilreamur=Double.toString(reamur);
        txtreamur.setText(hasilreamur);
        
        hasilcalvin=Double.toString(calvin);
        txtcalvin.setText(hasilcalvin);
           
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SuhuAwal2 = new javax.swing.JLabel();
        SuhuAwal = new javax.swing.JTextField();
        Celcius = new javax.swing.JRadioButton();
        Fahrenheint = new javax.swing.JRadioButton();
        Reamur = new javax.swing.JRadioButton();
        Calvin = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtcelcius = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtfahrenheit = new javax.swing.JTextField();
        txtreamur = new javax.swing.JTextField();
        txtcalvin = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        SuhuAwal2.setText("Suhu Awal");

        SuhuAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SuhuAwalActionPerformed(evt);
            }
        });

        Celcius.setText("Celcius");
        Celcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CelciusActionPerformed(evt);
            }
        });

        Fahrenheint.setText("Fahrenheint");

        Reamur.setText("Reamur");

        Calvin.setText("Calvin");

        jButton1.setText("Resault");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Celcius");

        txtcelcius.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcelciusActionPerformed(evt);
            }
        });

        jLabel3.setText("Fahrenheit");

        jLabel4.setText("Reamur");

        jLabel5.setText("Calvin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Celcius)
                        .addGap(18, 18, 18)
                        .addComponent(Fahrenheint)
                        .addGap(18, 18, 18)
                        .addComponent(Reamur)
                        .addGap(18, 18, 18)
                        .addComponent(Calvin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(SuhuAwal2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(SuhuAwal))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtreamur, javax.swing.GroupLayout.DEFAULT_SIZE, 231, Short.MAX_VALUE)
                            .addComponent(txtcelcius)
                            .addComponent(txtfahrenheit)
                            .addComponent(txtcalvin))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SuhuAwal2)
                    .addComponent(SuhuAwal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Celcius)
                    .addComponent(Fahrenheint)
                    .addComponent(Reamur)
                    .addComponent(Calvin))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcelcius, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtfahrenheit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtreamur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtcalvin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SuhuAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SuhuAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SuhuAwalActionPerformed

    private void CelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CelciusActionPerformed

    private void txtcelciusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcelciusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcelciusActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                if (Celcius.isSelected()){
            celcius();
        }
                else if (Fahrenheit.isSelected()) {
                    fahrenheit();
                }
        else if (Reamur.isSelected()) {
            reamur();
        }
        else if (Calvin.isSelected()) {
            calvin();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KonversiSuhuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KonversiSuhuu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Calvin;
    private javax.swing.JRadioButton Celcius;
    private javax.swing.JRadioButton Fahrenheint;
    private javax.swing.JRadioButton Reamur;
    private javax.swing.JTextField SuhuAwal;
    private javax.swing.JLabel SuhuAwal2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtcalvin;
    private javax.swing.JTextField txtcelcius;
    private javax.swing.JTextField txtfahrenheit;
    private javax.swing.JTextField txtreamur;
    // End of variables declaration//GEN-END:variables
}
